### ISSUE TITLE
different currency

### ISSUE THREAD

**Issue by ayushin** [rbii-incorporated/stripe_native#1]
Hi,

I've been looking in different places but I can't seem to figure out how to support Apple Pay / Google Pay in a currency different from USD?

Ultimately I would like to pass currency to Order() constructor.

Not even sure if Stripe plugin supports it. Any pointers?

**Comment by jnblanchard** [comment]
I think, it's possible, the charge api will take an ISO currency code. I'll look at the front-end side really quick and get back to you shortly.

**Comment by jnblanchard** [comment]
It looks like I can!
Stripe.paymentRequest(withMerchantIdentifier: identifier, country: "US", currency: "USD")

Do you have a country and currency that you'd like me to patch in quickly for you?

**Comment by jnblanchard** [comment]
And on Android we have the same!

.put("currencyCode", "USD")

**Comment by ayushin** [comment]
yes, that's not a problem with Stripe, I would like to use a different currency with Apple Pay i.e.             `var token = await StripeNative.useNativePay(nativeOrder);`

**Comment by jnblanchard** [comment]
You got it.

**Comment by ayushin** [comment]
Sorry, I still don't quite get how to pass the currency to the useNativePay method?

**Comment by jnblanchard** [comment]
There is no way currently, I will have to patch it in. I'll push it in the next few hours

**Comment by jnblanchard** [comment]
I am working on it now =D

**Comment by ayushin** [comment]
ah cool! let me know if i can help you in any way - but i'll test it at least :) right now interested in EUR and CZK

**Comment by jnblanchard** [comment]
I just pushed a version 1.1.0, there are two new methods you'll need for Apple Pay. 

```dart
StripeNative.setCurrencyKey("EUR");
// Not required on Android
StripeNative.setCountryKey("FR");
```

Just call these prior to useNativePay, and I hope it all works!

**Comment by ayushin** [comment]
Sounds good, but the plugin doesn't compile anymore:

```
stripe_native Group
Swift Compiler Error Group
/usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_native-1.1.0/ios/Classes/SwiftStripeNativePlugin.swift:59:42: Value of optional type 'String?' must be unwrapped to a value of type 'String'
/usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_native-1.1.0/ios/Classes/SwiftStripeNativePlugin.swift:59:42: Coalesce using '??' to provide a default when the optional value contains 'nil'
/usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_native-1.1.0/ios/Classes/SwiftStripeNativePlugin.swift:59:42: Force-unwrap using '!' to abort execution if the optional value contains 'nil'
/usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_native-1.1.0/ios/Classes/SwiftStripeNativePlugin.swift:63:41: Value of optional type 'String?' must be unwrapped to a value of type 'String'
/usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_native-1.1.0/ios/Classes/SwiftStripeNativePlugin.swift:63:41: Coalesce using '??' to provide a default when the optional value contains 'nil'
/usr/local/Caskroom/flutter/latest/flutter/.pub-cache/hosted/pub.dartlang.org/stripe_native-1.1.0/ios/Classes/SwiftStripeNativePlugin.swift:63:41: Force-unwrap using '!' to abort execution if the optional value contains 'nil'
```

**Comment by jnblanchard** [comment]
oops, let me fix that

**Comment by jnblanchard** [comment]
I believe 1.1.1 will fix that, I am sorry. I just pushed it

**Comment by jnblanchard** [comment]
And thank you!

**Comment by ayushin** [comment]
yeah i fixed it too - seems to work so far, awesome job!

i'll do more testing tomorrow (with server side integration) and report back

**Comment by jnblanchard** [comment]
I am happy to help anytime! Thank you very much

**Comment by jnblanchard** [comment]
I'll try to write a small server-side example too

**Comment by Pragya007** [comment]
@jnblanchard Can you help me out with google pay integration of this?
It is saying there is no merchant cards available to use with this merchant.

**Comment by ayushin** [comment]
@Pragya007 you may have better luck with https://pub.dev/packages/stripe_payment

**Comment by Pragya007** [comment]
For google pay there is no implementation every package is saying the same @ayushin

**Comment by Pragya007** [comment]
This package is having many issues

**Comment by ayushin** [comment]
I've been using stripe_payment for over a year and now it also comes with native pay support for Safari, but its up to you ;-) (Google play is supported too)

**Comment by Pragya007** [comment]
Have you tried with google pay? Same error I am getting I have google pay cards in my phone then also upon testing it is saying the same, I am using Stripe gateway..

**Comment by ayushin** [comment]
@Pragya007 this is not the place to discuss https://pub.dev/packages/stripe_payment (the package I am using) - if you have problems with that package - you should discuss it there

**Comment by jnblanchard** [comment]
Stripe payment is a great fully detailed package implementation of tipsi stripe. 

This issue is being closed because currency support has been solved.
