### ISSUE TITLE
IOS build issue with stripe_native 1.1.1

### ISSUE THREAD

**Issue by softkot** [rbii-incorporated/stripe_native#2]
When i try to build release with
flutter build ios --release 
it ends with 
fatal error: 'stripe_native/StripeNativePlugin.h' file not found
    #import <stripe_native/StripeNativePlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

while starts with 
 === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Target 'Pods-Runner' of project 'Pods' was rejected as an implicit dependency for 'Pods_Runner.framework' because its architectures 'arm64' didn't contain all required architectures
    'armv7 arm64'
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Release ===
    Building AOT snapshot in release mode (ios-release)...          
    Building App.framework for arm64...

    Building App.framework for armv7...
    Building AOT snapshot in release mode (ios-release)...             70.7s
    Built to build/aot/.

Here is the [demo](https://drive.google.com/file/d/1DFaMNbFOc9J7qZMMbKNEJCb7j9h0dH5u/view)

**Comment by jnblanchard** [comment]
Soo I started off by deleted the iOS folder inside my test project. (flutter create uses obj-c integration and the plugin is in swift.)
`flutter create -i swift .`

I went into Runner.xcworkspace and changed the deployment target to > 11.0. And added a development team.

And then I ran, pub get from the top level
`flutter pub get`

I edited the podfile, mine has a swift version at the bottom and a deployment part at the top, with use_framework in the middles. You can just copy this one.


![Screen Shot 2019-10-11 at 12 28 21 PM](https://user-images.githubusercontent.com/7946558/66679250-a69f1f00-ec22-11e9-97c3-599300ac7ffb.png)


The final thing was going into the iOS folder and running pod install.
`pod install`

**Comment by jnblanchard** [comment]
I have to find a way to add that podfile so it's easier to use

**Comment by softkot** [comment]
Meanwhile the latest flutter 1.9 has swift as default ios language.

All you suggestions above does not helps me to success build the simple demo from my video.

**Comment by jnblanchard** [comment]
Dang, I'll keep trying stuff. Maybe I missed a step XD

I posted an example [here](https://github.com/jnblanchard/plugin_test)

Does this example complain about iOS-architecture too??

Thanks again

**Comment by softkot** [comment]
It does not complain about arch but fails the same way with file not found error

```
bash-3.2$ flutter build ios --debug
Building com.example.pluginTest for device (ios)...
Automatically signing iOS for device deployment using specified development team in Xcode project: 694JMGS3ZC
Running pod install...                                              2.5s
Running Xcode build...                                                  
                                                   
 ├─Assembling Flutter resources...                           9.6s
 └─Compiling, linking and signing...                         1.7s
Xcode build done.                                           14.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/softkot/Projects/plugin_test/ios/Runner/GeneratedPluginRegistrant.m:6:9: fatal error:
    'stripe_native/StripeNativePlugin.h' file not found
    #import <stripe_native/StripeNativePlugin.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build systemnote: Planning buildnote: Constructing build description



```
