### ISSUE TITLE
Unable to make a real payment on Android

### ISSUE THREAD

**Issue by softkot** [rbii-incorporated/stripe_native#3]
Android code always use WalletConstants.ENVIRONMENT_TEST environment regardless of publishable key type pk_live or pk_test

**Comment by jnblanchard** [comment]
Thank you again very much, with 1.1.2 I used your idea of checking publishable key to change the environment.

**Comment by Pragya007** [comment]
@jnblanchard  Is possible to add google pay bottom sheet from this plugin?

**Comment by Pragya007** [comment]
I did it and running on android it is saying no cards available for use this merchant.....although my gmail has gpay connected with it.

**Comment by jnblanchard** [comment]
@Pragya007 This is not appropriate as a part of this issue.

If all these packages are failing the problems is likely with your card’s connection to google pay.

https://youtu.be/PQqLPuf3vGs
https://support.google.com/store/answer/6160259?hl=en
