### ISSUE TITLE
StripeNative.useReceiptNativePay returns empty token

### ISSUE THREAD

**Issue by softkot** [rbii-incorporated/stripe_native#4]
On ios the returned token is empty if country code is invalid instead of detailed exception

      StripeNative.useReceiptNativePay(receipt).then((cardtoken) {
        print("CARD TOKEN: " + cardtoken); // is empty
        StripeNative.confirmPayment(true);
      }).catchError((e) {
        print(e.toString());
        StripeNative.confirmPayment(false);
        withErrorDlg(e, context);
      });

**Comment by jnblanchard** [comment]
I’ll add something there, there may be the same problem with invalid currency. Thank you as always

**Comment by jnblanchard** [comment]
with 1.1.3 (iOS pod 1.0.1) there is a country key error for receipt and order made native pays.

CountryKeyIsInvalid will be the error

Thanks again

**Comment by softkot** [comment]
You have wrong approach to handle errors. The first thing you have to to with any error return it as FlutterError object into flutterResult

**Comment by softkot** [comment]
You new checks for country and currency does not actually works thus always returns false. Please revew the way you handle all that stuff and keep the validation to payment framework paying attention to proper exception return to flutter with all details. And please try to test it firts prior to commit it.

**Comment by jnblanchard** [comment]
I apologize for breaking everything, that was quite sloppy on my part. With 1.1.4 plugin, and 1.0.2 pod, I hope you find FlutterErrors useful and the country key failures gone. As always thank you very much, I appreciate you a ton.

**Comment by jnblanchard** [comment]
On my todo is to move that same functionality over to the android side.
